// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: proto/gateway.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatMessage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SenderId        string                 `protobuf:"bytes,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ReceiverId      string                 `protobuf:"bytes,2,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	Content         string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ClientTimestamp int64                  `protobuf:"varint,4,opt,name=client_timestamp,json=clientTimestamp,proto3" json:"client_timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_proto_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *ChatMessage) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *ChatMessage) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessage) GetClientTimestamp() int64 {
	if x != nil {
		return x.ClientTimestamp
	}
	return 0
}

type PersistedMessage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Message         *ChatMessage           `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ReceiverPts     int64                  `protobuf:"varint,3,opt,name=receiver_pts,json=receiverPts,proto3" json:"receiver_pts,omitempty"`
	SenderPts       int64                  `protobuf:"varint,4,opt,name=sender_pts,json=senderPts,proto3" json:"sender_pts,omitempty"`
	ServerTimestamp int64                  `protobuf:"varint,5,opt,name=server_timestamp,json=serverTimestamp,proto3" json:"server_timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PersistedMessage) Reset() {
	*x = PersistedMessage{}
	mi := &file_proto_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersistedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersistedMessage) ProtoMessage() {}

func (x *PersistedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersistedMessage.ProtoReflect.Descriptor instead.
func (*PersistedMessage) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *PersistedMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PersistedMessage) GetMessage() *ChatMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *PersistedMessage) GetReceiverPts() int64 {
	if x != nil {
		return x.ReceiverPts
	}
	return 0
}

func (x *PersistedMessage) GetSenderPts() int64 {
	if x != nil {
		return x.SenderPts
	}
	return 0
}

func (x *PersistedMessage) GetServerTimestamp() int64 {
	if x != nil {
		return x.ServerTimestamp
	}
	return 0
}

type DeliveryAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delivered     bool                   `protobuf:"varint,1,opt,name=delivered,proto3" json:"delivered,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryAck) Reset() {
	*x = DeliveryAck{}
	mi := &file_proto_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryAck) ProtoMessage() {}

func (x *DeliveryAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryAck.ProtoReflect.Descriptor instead.
func (*DeliveryAck) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *DeliveryAck) GetDelivered() bool {
	if x != nil {
		return x.Delivered
	}
	return false
}

type GetDiffRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ClientPts     int64                  `protobuf:"varint,2,opt,name=client_pts,json=clientPts,proto3" json:"client_pts,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiffRequest) Reset() {
	*x = GetDiffRequest{}
	mi := &file_proto_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiffRequest) ProtoMessage() {}

func (x *GetDiffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiffRequest.ProtoReflect.Descriptor instead.
func (*GetDiffRequest) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *GetDiffRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetDiffRequest) GetClientPts() int64 {
	if x != nil {
		return x.ClientPts
	}
	return 0
}

func (x *GetDiffRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetDiffResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*PersistedMessage    `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	CurrentPts    int64                  `protobuf:"varint,2,opt,name=current_pts,json=currentPts,proto3" json:"current_pts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiffResponse) Reset() {
	*x = GetDiffResponse{}
	mi := &file_proto_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiffResponse) ProtoMessage() {}

func (x *GetDiffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiffResponse.ProtoReflect.Descriptor instead.
func (*GetDiffResponse) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *GetDiffResponse) GetMessages() []*PersistedMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *GetDiffResponse) GetCurrentPts() int64 {
	if x != nil {
		return x.CurrentPts
	}
	return 0
}

type PtsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PtsRequest) Reset() {
	*x = PtsRequest{}
	mi := &file_proto_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PtsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PtsRequest) ProtoMessage() {}

func (x *PtsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PtsRequest.ProtoReflect.Descriptor instead.
func (*PtsRequest) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *PtsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type PtsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pts           int64                  `protobuf:"varint,1,opt,name=pts,proto3" json:"pts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PtsResponse) Reset() {
	*x = PtsResponse{}
	mi := &file_proto_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PtsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PtsResponse) ProtoMessage() {}

func (x *PtsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PtsResponse.ProtoReflect.Descriptor instead.
func (*PtsResponse) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *PtsResponse) GetPts() int64 {
	if x != nil {
		return x.Pts
	}
	return 0
}

var File_proto_gateway_proto protoreflect.FileDescriptor

const file_proto_gateway_proto_rawDesc = "" +
	"\n" +
	"\x13proto/gateway.proto\x12\ftinytelegram\"\x90\x01\n" +
	"\vChatMessage\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\tR\bsenderId\x12\x1f\n" +
	"\vreceiver_id\x18\x02 \x01(\tR\n" +
	"receiverId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12)\n" +
	"\x10client_timestamp\x18\x04 \x01(\x03R\x0fclientTimestamp\"\xc4\x01\n" +
	"\x10PersistedMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x123\n" +
	"\amessage\x18\x02 \x01(\v2\x19.tinytelegram.ChatMessageR\amessage\x12!\n" +
	"\freceiver_pts\x18\x03 \x01(\x03R\vreceiverPts\x12\x1d\n" +
	"\n" +
	"sender_pts\x18\x04 \x01(\x03R\tsenderPts\x12)\n" +
	"\x10server_timestamp\x18\x05 \x01(\x03R\x0fserverTimestamp\"+\n" +
	"\vDeliveryAck\x12\x1c\n" +
	"\tdelivered\x18\x01 \x01(\bR\tdelivered\"^\n" +
	"\x0eGetDiffRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"client_pts\x18\x02 \x01(\x03R\tclientPts\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"n\n" +
	"\x0fGetDiffResponse\x12:\n" +
	"\bmessages\x18\x01 \x03(\v2\x1e.tinytelegram.PersistedMessageR\bmessages\x12\x1f\n" +
	"\vcurrent_pts\x18\x02 \x01(\x03R\n" +
	"currentPts\"%\n" +
	"\n" +
	"PtsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x1f\n" +
	"\vPtsResponse\x12\x10\n" +
	"\x03pts\x18\x01 \x01(\x03R\x03pts2]\n" +
	"\x0eGatewayService\x12K\n" +
	"\x0eDeliverMessage\x12\x1e.tinytelegram.PersistedMessage\x1a\x19.tinytelegram.DeliveryAck2\xe8\x01\n" +
	"\x0eMessageService\x12K\n" +
	"\x0ePersistMessage\x12\x19.tinytelegram.ChatMessage\x1a\x1e.tinytelegram.PersistedMessage\x12F\n" +
	"\aGetDiff\x12\x1c.tinytelegram.GetDiffRequest\x1a\x1d.tinytelegram.GetDiffResponse\x12A\n" +
	"\n" +
	"GetUserPts\x12\x18.tinytelegram.PtsRequest\x1a\x19.tinytelegram.PtsResponseB\x14Z\x12tinytelegram/protob\x06proto3"

var (
	file_proto_gateway_proto_rawDescOnce sync.Once
	file_proto_gateway_proto_rawDescData []byte
)

func file_proto_gateway_proto_rawDescGZIP() []byte {
	file_proto_gateway_proto_rawDescOnce.Do(func() {
		file_proto_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gateway_proto_rawDesc), len(file_proto_gateway_proto_rawDesc)))
	})
	return file_proto_gateway_proto_rawDescData
}

var file_proto_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_gateway_proto_goTypes = []any{
	(*ChatMessage)(nil),      // 0: tinytelegram.ChatMessage
	(*PersistedMessage)(nil), // 1: tinytelegram.PersistedMessage
	(*DeliveryAck)(nil),      // 2: tinytelegram.DeliveryAck
	(*GetDiffRequest)(nil),   // 3: tinytelegram.GetDiffRequest
	(*GetDiffResponse)(nil),  // 4: tinytelegram.GetDiffResponse
	(*PtsRequest)(nil),       // 5: tinytelegram.PtsRequest
	(*PtsResponse)(nil),      // 6: tinytelegram.PtsResponse
}
var file_proto_gateway_proto_depIdxs = []int32{
	0, // 0: tinytelegram.PersistedMessage.message:type_name -> tinytelegram.ChatMessage
	1, // 1: tinytelegram.GetDiffResponse.messages:type_name -> tinytelegram.PersistedMessage
	1, // 2: tinytelegram.GatewayService.DeliverMessage:input_type -> tinytelegram.PersistedMessage
	0, // 3: tinytelegram.MessageService.PersistMessage:input_type -> tinytelegram.ChatMessage
	3, // 4: tinytelegram.MessageService.GetDiff:input_type -> tinytelegram.GetDiffRequest
	5, // 5: tinytelegram.MessageService.GetUserPts:input_type -> tinytelegram.PtsRequest
	2, // 6: tinytelegram.GatewayService.DeliverMessage:output_type -> tinytelegram.DeliveryAck
	1, // 7: tinytelegram.MessageService.PersistMessage:output_type -> tinytelegram.PersistedMessage
	4, // 8: tinytelegram.MessageService.GetDiff:output_type -> tinytelegram.GetDiffResponse
	6, // 9: tinytelegram.MessageService.GetUserPts:output_type -> tinytelegram.PtsResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_gateway_proto_init() }
func file_proto_gateway_proto_init() {
	if File_proto_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gateway_proto_rawDesc), len(file_proto_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_gateway_proto_goTypes,
		DependencyIndexes: file_proto_gateway_proto_depIdxs,
		MessageInfos:      file_proto_gateway_proto_msgTypes,
	}.Build()
	File_proto_gateway_proto = out.File
	file_proto_gateway_proto_goTypes = nil
	file_proto_gateway_proto_depIdxs = nil
}
