services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: tt_user
      POSTGRES_PASSWORD: tt_pass
      POSTGRES_DB: tinytelegram
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tt_user -d tinytelegram"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.1gw.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - gateway1

  gateway1:
    build: ../gateway
    environment:
      - REDIS_ADDR=redis:6379
      - PORT=8080
      - GRPC_PORT=9000
      - GATEWAY_ADDR=gateway1:8080
      - GATEWAY_GRPC_ADDR=gateway1:9000
      - MSG_SERVICE_ADDR=message-service:5050
    depends_on:
      - redis

  message-service:
    build: ../message-service
    environment:
      - REDIS_ADDR=redis:6379
      - POSTGRES_DSN=postgres://tt_user:tt_pass@postgres:5432/tinytelegram?sslmode=disable
      - PORT=9090
      - GRPC_PORT=5050
    ports:
      - "9090:9090"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

volumes:
  postgres_data:
